# Generated by Django 4.2.29 on 2026-03-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=500, unique=True)),
                ('name_ru', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
