# Generated by Django 4.2.29 on 2026-03-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.singer'),
        ),
    ]
