# Generated by Django 4.2.29 on 2026-03-24 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_track_audio_file_alter_track_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.artist'),
        ),
    ]
